### ISSUE TITLE
nUnknown command

### ISSUE THREAD

**Issue by gunaone** [sapzxc/airbag-fix#1]
i just input w/write or r/read and i get nothing

i use ic 93c86, 
how about pi 6..? 1 or 0..?

**Comment by sapzxc** [comment]
look at code

```
if(Serial.available() > 0) 
  {
    String s = Serial.readString();
    s.toLowerCase();
    
    if(s=="write" || s=="w")
    {
      Serial.print("\nwriting...\n");
      writeEeprom();
    }
    else if(s=="read" || s=="r")
    {
      Serial.print("\nreading...\n");
      readEeprom();
    }
    else
    {
      Serial.print("\nUnknown command [");
      Serial.print(s);
      Serial.print("]\n");
      Serial.print("Help: \n"
        "write  - write dump\n"
      );
    }
  }
```

Looks like you have another string in input. You can change input as you wish. This code was tested on Arduino Uno. Maybe in your device it can be "w\n" - like with enter?

**Comment by gunaone** [comment]
hy @sapzxc 

===WRITING (1024:8) ===
DUMP:
 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 5a5a 5a5a a5a5 a5a5
===

000 -> 00 => ok. 
001 -> 00 => ok. 
002 -> 00 => ok. 
003 -> 00 => ok. 
004 -> 00 => ok. 
005 -> 00 => ok. 
006 -> 00 => ok. 
007 -> 00 => ok. 
008 -> 00 => ok. 
009 -> 00 => ok. 
010 -> 00 => ok. 
011 -> 00 => ok. 
012 -> 00 => ok. 
013 -> 00 => ok. 
014 -> 00 => ok. 
015 -> 00 => ok. 
016 -> 00 => ok. 
017 -> 00 => ok. 
018 -> 00 => ok. 
019 -> 00 => ok. 
020 -> 00 => ok. 
021 -> 00 => ok. 
022 -> 00 => ok. 
023 -> 00 => ok. 
024 -> 00 => ok. 
025 -> 00 => ok. 
026 -> 00 => ok. 
027 -> 00 => ok. 
028 -> 00 => ok. 
029 -> 00 => ok. 
030 -> 00 => ok. 
031 -> 00 => ok. 
032 -> 00 => ok. 
033 -> 00 => ok. 
034 -> 00 => ok. 
035 -> 00 => ok. 
036 -> 00 => ok. 
037 -> 00 => ok. 
038 -> 00 => ok. 
039 -> 00 => ok. 
040 -> 00 => ok. 
041 -> 00 => ok. 
042 -> 00 => ok. 
043 -> 00 => ok. 
044 -> 00 => ok. 
045 -> 00 => ok. 
046 -> 00 => ok. 
047 -> 00 => ok. 
048 -> 00 => ok. 
049 -> 00 => ok. 
050 -> 00 => ok. 
051 -> 00 => ok. 
052 -> 00 => ok. 
053 -> 00 => ok. 
054 -> 00 => ok. 
055 -> 00 => ok. 
056 -> 00 => ok. 
057 -> 00 => ok. 
058 -> 00 => ok. 
059 -> 00 => ok. 
060 -> 00 => ok. 
061 -> 00 => ok. 
062 -> 00 => ok. 
063 -> 00 => ok. 
064 -> 00 => ok. 
065 -> 00 => ok. 
066 -> 00 => ok. 
067 -> 00 => ok. 
068 -> 00 => ok. 
069 -> 00 => ok. 
070 -> 00 => ok. 
071 -> 00 => ok. 
072 -> 00 => ok. 
073 -> 00 => ok. 
074 -> 00 => ok. 
075 -> 00 => ok. 
076 -> 00 => ok. 
077 -> 00 => ok. 
078 -> 00 => ok. 
079 -> 00 => ok. 
080 -> 00 => ok. 
081 -> 00 => ok. 
082 -> 00 => ok. 
083 -> 00 => ok. 
084 -> 00 => ok. 
085 -> 00 => ok. 
086 -> 00 => ok. 
087 -> 00 => ok. 
088 -> 00 => ok. 
089 -> 00 => ok. 
090 -> 00 => ok. 
091 -> 00 => ok. 
092 -> 00 => ok. 
093 -> 00 => ok. 
094 -> 00 => ok. 
095 -> 00 => ok. 
096 -> 00 => ok. 
097 -> 00 => ok. 
098 -> 00 => ok. 
099 -> 00 => ok. 
100 -> 00 => ok. 
101 -> 00 => ok. 
102 -> 00 => ok. 
103 -> 00 => ok. 
104 -> 00 => ok. 
105 -> 00 => ok. 
106 -> 00 => ok. 
107 -> 00 => ok. 
108 -> 00 => ok. 
109 -> 00 => ok. 
110 -> 00 => ok. 
111 -> 00 => ok. 
112 -> 00 => ok. 
113 -> 00 => ok. 
114 -> 00 => ok. 
115 -> 00 => ok. 
116 -> 00 => ok. 
117 -> 00 => ok. 
118 -> 00 => ok. 
119 -> 00 => ok. 
120 -> 5a => ok. 
121 -> 5a => ok. 
122 -> 5a => ok. 
123 -> 5a => ok. 
124 -> a5 => ok. 
125 -> a5 => ok. 
126 -> a5 => ok. 
127 -> a5 => ok. 

delay(200)

===END WRITING===
===START DUMP (1024:8) === 
ffff ffff ffff 0000 00ff ffff ffff 0000  
00ff ffff ffff 0000 00ff ffff ffff 0000  
00ff ffff ffff 0000 00ff ffff ffff 0000  
00ff ffff ffff 0000 00ff ffff ffff 0000  
00ff ffff ffff 0000 00ff ffff ffff 0000  
00ff ffff ffff f000 00ff ffff ffff ff00  
00ff ffff ffff ff00 00ff ffff ffff ff00  
00ff ffff ffff ff00 007f ffff ffff ff00  

===END DUMP===

===WRITING (1024:8) ===
DUMP:
 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 5a5a 5a5a a5a5 a5a5
===

000 -> 00 => ok. 
001 -> 00 => ok. 
002 -> 00 => ok. 
003 -> 00 => ok. 
004 -> 00 => ok. 
005 -> 00 => ok. 
006 -> 00 => ok. 
007 -> 00 => ok. 
008 -> 00 => ok. 
009 -> 00 => ok. 
010 -> 00 => ok. 
011 -> 00 => ok. 
012 -> 00 => ok. 
013 -> 00 => ok. 
014 -> 00 => ok. 
015 -> 00 => ok. 
016 -> 00 => ok. 
017 -> 00 => ok. 
018 -> 00 => ok. 
019 -> 00 => ok. 
020 -> 00 => ok. 
021 -> 00 => ok. 
022 -> 00 => ok. 
023 -> 00 => ok. 
024 -> 00 => ok. 
025 -> 00 => ok. 
026 -> 00 => ok. 
027 -> 00 => ok. 
028 -> 00 => ok. 
029 -> 00 => ok. 
030 -> 00 => ok. 
031 -> 00 => ok. 
032 -> 00 => ok. 
033 -> 00 => ok. 
034 -> 00 => ok. 
035 -> 00 => ok. 
036 -> 00 => ok. 
037 -> 00 => ok. 
038 -> 00 => ok. 
039 -> 00 => ok. 
040 -> 00 => ok. 
041 -> 00 => ok. 
042 -> 00 => ok. 
043 -> 00 => ok. 
044 -> 00 => ok. 
045 -> 00 => ok. 
046 -> 00 => ok. 
047 -> 00 => ok. 
048 -> 00 => ok. 
049 -> 00 => ok. 
050 -> 00 => ok. 
051 -> 00 => ok. 
052 -> 00 => ok. 
053 -> 00 => ok. 
054 -> 00 => ok. 
055 -> 00 => ok. 
056 -> 00 => ok. 
057 -> 00 => ok. 
058 -> 00 => ok. 
059 -> 00 => ok. 
060 -> 00 => ok. 
061 -> 00 => ok. 
062 -> 00 => ok. 
063 -> 00 => ok. 
064 -> 00 => ok. 
065 -> 00 => ok. 
066 -> 00 => ok. 
067 -> 00 => ok. 
068 -> 00 => ok. 
069 -> 00 => ok. 
070 -> 00 => ok. 
071 -> 00 => ok. 
072 -> 00 => ok. 
073 -> 00 => ok. 
074 -> 00 => ok. 
075 -> 00 => ok. 
076 -> 00 => ok. 
077 -> 00 => ok. 
078 -> 00 => ok. 
079 -> 00 => ok. 
080 -> 00 => ok. 
081 -> 00 => ok. 
082 -> 00 => ok. 
083 -> 00 => ok. 
084 -> 00 => ok. 
085 -> 00 => ok. 
086 -> 00 => ok. 
087 -> 00 => ok. 
088 -> 00 => ok. 
089 -> 00 => ok. 
090 -> 00 => ok. 
091 -> 00 => ok. 
092 -> 00 => ok. 
093 -> 00 => ok. 
094 -> 00 => ok. 
095 -> 00 => ok. 
096 -> 00 => ok. 
097 -> 00 => ok. 
098 -> 00 => ok. 
099 -> 00 => ok. 
100 -> 00 => ok. 
101 -> 00 => ok. 
102 -> 00 => ok. 
103 -> 00 => ok. 
104 -> 00 => ok. 
105 -> 00 => ok. 
106 -> 00 => ok. 
107 -> 00 => ok. 
108 -> 00 => ok. 
109 -> 00 => ok. 
110 -> 00 => ok. 
111 -> 00 => ok. 
112 -> 00 => ok. 
113 -> 00 => ok. 
114 -> 00 => ok. 
115 -> 00 => ok. 
116 -> 00 => ok. 
117 -> 00 => ok. 
118 -> 00 => ok. 
119 -> 00 => ok. 
120 -> 5a => ok. 
121 -> 5a => ok. 
122 -> 5a => ok. 
123 -> 5a => ok. 
124 -> a5 => ok. 
125 -> a5 => ok. 
126 -> a5 => ok. 
127 -> a5 => ok. 

delay(200)

===END WRITING===
===START DUMP (1024:8) === 
ffff 0000 00ff ffff ffff 0000 00ff ffff  
ffff 0000 00ff ffff ffff 0000 00ff ffff  
ffff 0000 00ff ffff ffff 0000 00ff ffff  
ffff 0000 00ff ffff ffff 0000 00ff ffff  
ffff f000 00ff ffff ffff ff00 00ff ffff  
ffff ff00 00ff ffff ffff ff00 00ff ffff  
ffff ff00 007f ffff ffff ff00 001f ffff  
ffff ff00 0000 ffff ffff ff00 0000 ffff  

===END DUMP===

i was try to read and write directly, but i get difference write and read. i try to push reset twice

**Comment by gunaone** [comment]
i use 93C76 and 9386......

**Comment by sapzxc** [comment]
looks like you have some wrong settings or contacts. Looks like your result data is actually synced with some 1 and 0 not synchronized with clock. Like ffff 0000 its like 1 0 but stretched in time. OR clock pin has not synced with data. Look at read/write diagram of your chip.

Actually I tested it on 93c46. Also when I was working with this chips I have different "pictures" with the same marked chips, but developed by different manufacturer. You should play with settings, read datasheet and try to make it works.

**Comment by gunaone** [comment]
@sapzxc ok, thanks for your suggestions.....
